#ifndef _MUSICPLAYER_STATUS_H_
#define _MUSICPLAYER_STATUS_H_

#define PCM_DEVICE "plughw:0,0"
#define PAUSE_STATE 1
#define PLAY_STATE 2
#define STOP_STATE 3

typedef enum {
MUSICPLAYER_SUCCESS = 0,
MUSICPLAYER_FAILURE = -1,
MUSICPLAYER_INPUT_RANGE_EXCEEDED =1,
MUSICPLAYER_FILES_NOT_FOUND=2,
MUSICPLAYER_INVALID_FILE_NAME=3,
MUSICPLAYERUNABLE_TO_OPEN_THE_FILE=4,
MUSICPLAYER_HARDWARE_INTIALISATION_ERROR=5 ,
UNABLE_TO_OPEN_THE_PCM_DEVICE=6 ,
MUSICPLAYER_STOP_STATE=7,   
MUSICPLAYER_SEEK_EXCEEDS_DURATION=8,
MUSICPLAYER_SEEK_DECEEDS_DURATION=9 ,
MUSICPLAYER_VOLUME_EXCEEDS_90=10 ,
MUSICPLAYER_VOLUME_DECEEDS_0=11 ,
MUSICPLAYER_NO_NEXT_FILES=12 ,
MUSICPLAYER_NO_PREV_FILES=13
}eMusicPlayer_status;

pthread_t pThread_id, pThread_id1;
#endif
 
